const fs = require('fs');

const products = [
  {id:'RB-001',slug:'custom-round-perfume-gift-box',folder:'RB-001_round-perfume-gift-box',name:'Custom Round Perfume Gift Box with Shoulder-Neck Lid',title:'Custom Round Perfume Gift Box Manufacturer | ShineleeBox',application:'perfume and fragrance launches',structure:'shoulder-neck two-piece cylinder',finish:'burgundy textured paper with gold foil',insert:'custom EVA, card or velvet-covered insert',desc:'Luxury round perfume gift box with a shoulder-neck lid, custom insert and foil branding. OEM cylindrical rigid packaging for fragrance brands and gift sets.'},
  {id:'RB-002',slug:'custom-round-candle-gift-box',folder:'RB-002_round-candle-gift-box',name:'Custom Round Candle Gift Box with Molded Pulp Insert',title:'Custom Round Candle Gift Box Manufacturer | ShineleeBox',application:'scented candles and home-fragrance collections',structure:'short two-piece rigid cylinder',finish:'forest-green paper with copper foil',insert:'molded pulp, card or EVA candle holder',desc:'Custom round candle gift box with protective molded-pulp insert and foil branding. Rigid cylindrical packaging for candle and home-fragrance brands.'},
  {id:'RB-003',slug:'luxury-round-jewelry-box',folder:'RB-003_round-jewelry-gift-box',name:'Luxury Round Jewelry Gift Box with Velvet Insert',title:'Luxury Round Jewelry Box Manufacturer | ShineleeBox',application:'rings, earrings and small jewelry gifts',structure:'compact shoulder-neck round box',finish:'pearl ivory paper with metallic rim detail',insert:'velvet-covered ring, earring or pendant insert',desc:'Luxury round jewelry gift box with a velvet insert and premium wrapped rigid-board construction. Custom cylindrical packaging for jewelry brands and retailers.'},
  {id:'RB-004',slug:'round-chocolate-box-with-window',folder:'RB-004_round-chocolate-window-box',name:'Custom Round Chocolate Box with Clear Window',title:'Round Chocolate Box with Window Manufacturer | ShineleeBox',application:'truffles, pralines and seasonal confectionery',structure:'wide round lid-and-base box with window',finish:'midnight-blue paper with gold foil',insert:'radial food-grade paper or PET tray',desc:'Custom round chocolate gift box with a clear lid window and radial compartments. OEM rigid packaging for truffles, pralines and seasonal confectionery.'},
  {id:'RB-005',slug:'custom-round-tea-tube-box',folder:'RB-005_round-tea-tube-box',name:'Custom Round Tea Tube Box with Telescoping Lid',title:'Custom Tea Tube Packaging Manufacturer | ShineleeBox',application:'loose-leaf tea, sachets and premium tea gifts',structure:'tall telescoping paper tube',finish:'sage and cream paper with embossed leaf pattern',insert:'pouch support, inner neck or food-safe liner option',desc:'Custom round tea tube packaging with a telescoping lid, embossed paper and branded printing. Premium cylindrical boxes for loose-leaf tea and gift sets.'},
  {id:'RB-006',slug:'custom-round-wine-bottle-tube',folder:'RB-006_round-wine-tube-box',name:'Custom Round Wine Bottle Tube with Rope Handle',title:'Custom Wine Bottle Tube Manufacturer | ShineleeBox',application:'wine, spirits and corporate bottle gifting',structure:'tall rigid bottle tube with carry rope',finish:'charcoal specialty paper with copper foil',insert:'neck support and protective base pad',desc:'Custom round wine bottle tube with rope handle, rigid grayboard structure and foil branding. Premium cylindrical packaging for wine, spirits and corporate gifts.'},
  {id:'RB-007',slug:'two-tier-round-cosmetic-box',folder:'RB-007_two-tier-round-cosmetic-box',name:'Two-Tier Round Cosmetic Gift Box with Pull Tabs',title:'Two-Tier Round Cosmetic Gift Box Manufacturer | ShineleeBox',application:'skincare routines, beauty launches and PR sets',structure:'stacked two-tier rigid cylinder',finish:'blush and terracotta printed paper',insert:'die-cut card, EVA or molded pulp cosmetic insert',desc:'Custom two-tier round cosmetic gift box with pull tabs and fitted skincare inserts. OEM cylindrical packaging for beauty launches, PR sets and gift collections.'},
  {id:'RB-008',slug:'round-flower-hat-box',folder:'RB-008_round-flower-hat-box',name:'Luxury Round Flower Hat Box with Ribbon Handles',title:'Luxury Round Flower Hat Box Manufacturer | ShineleeBox',application:'preserved flowers, event gifts and premium bouquets',structure:'large hat-box cylinder with lift-off lid',finish:'deep plum paper with rose-gold foil',insert:'flower liner, platform or gift-compartment option',desc:'Luxury round flower hat box with ribbon handles, rigid grayboard walls and foil branding. Custom packaging for preserved flowers, events and premium gifting.'},
  {id:'RB-009',slug:'custom-coffee-paper-tube',folder:'RB-009_round-coffee-tube-box',name:'Custom Coffee Paper Tube with Telescoping Lid',title:'Custom Coffee Paper Tube Manufacturer | ShineleeBox',application:'coffee beans, ground coffee and tasting gifts',structure:'tall telescoping rigid paper tube',finish:'kraft and matte-black paper with copper foil',insert:'sealed pouch support or food-safe liner option',desc:'Custom coffee paper tube with telescoping lid, kraft wrap and foil branding. Premium cylindrical packaging for beans, ground coffee and tasting gift sets.'},
  {id:'RB-010',slug:'round-macaron-drawer-box',folder:'RB-010_round-macaron-drawer-box',name:'Round Macaron Gift Box with Curved Drawer',title:'Round Macaron Drawer Box Manufacturer | ShineleeBox',application:'macarons, petits fours and luxury dessert gifts',structure:'round rigid box with curved pull-out drawer',finish:'pistachio and cream paper with gold foil',insert:'food-grade paper dividers or PET tray',desc:'Custom round macaron gift box with a curved pull-out drawer and fitted compartments. Original rigid packaging for macarons, petits fours and dessert gifts.'},
  {id:'RB-011',slug:'nesting-round-holiday-gift-boxes',folder:'RB-011-nesting-round-holiday-boxes',name:'Nesting Round Holiday Gift Box Set',title:'Nesting Round Gift Box Set Manufacturer | ShineleeBox',application:'Christmas, retail gifting and seasonal displays',structure:'three graduated two-piece round boxes',finish:'coordinated red, green and ivory paper with gold foil',insert:'optional card partitions, tissue or product platforms',desc:'Custom nesting round holiday gift box set in graduated sizes with coordinated printing and gold foil. OEM rigid packaging for Christmas and seasonal retail gifting.'},
  {id:'RB-012',slug:'round-essential-oil-discovery-box',folder:'RB-012_round-essential-oil-box',name:'Round Essential Oil Discovery Box with Fan-Opening Lid',title:'Round Essential Oil Gift Box Manufacturer | ShineleeBox',application:'essential oils, wellness kits and discovery sets',structure:'round rigid box with segmented fan-opening lid',finish:'deep teal textured paper with gold foil',insert:'radial card or EVA bottle insert',desc:'Custom round essential-oil discovery box with a fan-opening lid and radial bottle insert. Innovative cylindrical packaging for wellness and aromatherapy gift sets.'}
];

const esc = value => value.replaceAll('&','&amp;');
const productTemplate = fs.readFileSync('products/rg-001.html','utf8');

for (const p of products) {
  const url = `https://slpack.net/products/${p.slug}.html`;
  const schema = {
    '@context':'https://schema.org','@graph':[
      {'@type':'BreadcrumbList','@id':`${url}#breadcrumb`,itemListElement:[
        {'@type':'ListItem',position:1,name:'Home',item:'https://slpack.net/'},
        {'@type':'ListItem',position:2,name:'Round Gift Boxes',item:'https://slpack.net/products/rigid-boxes/round-gift-boxes.html'},
        {'@type':'ListItem',position:3,name:p.name,item:url}
      ]},
      {'@type':'Product','@id':`${url}#product`,name:p.name,description:p.desc,sku:p.id,url,category:'Rigid Gift Boxes > Round Gift Boxes',brand:{'@type':'Brand',name:'ShineleeBox'},manufacturer:{'@id':'https://slpack.net/#organization'},image:[`https://slpack.net/images/products/${p.folder}/main.webp`]},
      {'@type':'FAQPage',mainEntity:[
        {'@type':'Question',name:`Can the ${p.name.toLowerCase()} be customized?`,acceptedAnswer:{'@type':'Answer',text:`Yes. Buyers can customize dimensions, structure, wrapped paper, printing, finishing and the ${p.insert}.`}},
        {'@type':'Question',name:'What information is needed for a quotation?',acceptedAnswer:{'@type':'Answer',text:'Provide the packed product dimensions, target quantity, preferred structure, artwork status, insert requirements and delivery country.'}},
        {'@type':'Question',name:'What is the minimum order quantity?',acceptedAnswer:{'@type':'Answer',text:'MOQ depends on size, materials, printing, finishing and assembly. Selected custom projects may start from 50 pieces; confirm the applicable quantity during quotation.'}}
      ]}
    ]
  };
  const main = `<main class="flex-grow">
    <nav class="bg-white border-b border-slate-100 py-4 px-4"><div class="max-w-7xl mx-auto text-xs text-slate-500 font-medium flex items-center space-x-2"><a href="../index.html" class="hover:text-brandGold">Home</a><span>/</span><a href="rigid-boxes/round-gift-boxes.html" class="hover:text-brandGold">Round Gift Boxes</a><span>/</span><span class="text-slate-800 font-semibold">${p.id}</span></div></nav>
    <section class="py-14 sm:py-16 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div class="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
      <div class="lg:col-span-6 lg:sticky lg:top-24"><div class="aspect-square bg-white rounded-lg overflow-hidden border border-slate-200 shadow-sm"><img src="../images/products/${p.folder}/main.webp" alt="${esc(p.name)} by ShineleeBox" class="w-full h-full object-contain"></div></div>
      <div class="lg:col-span-6 space-y-8"><div><p class="text-[10px] text-brandGold font-bold uppercase tracking-[0.2em] mb-3">${p.id} · Custom OEM Packaging</p><h1 class="font-serif text-3xl sm:text-4xl font-bold text-brandCharcoal mb-4">${esc(p.name)}</h1><p class="text-lg text-slate-600 font-light leading-relaxed">${p.desc}</p></div>
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm"><div class="bg-brandIvory border border-brandBeige p-5"><strong class="block mb-2">Structure</strong><span class="text-slate-600">${p.structure}</span></div><div class="bg-brandIvory border border-brandBeige p-5"><strong class="block mb-2">Best for</strong><span class="text-slate-600">${p.application}</span></div><div class="bg-brandIvory border border-brandBeige p-5"><strong class="block mb-2">Finish direction</strong><span class="text-slate-600">${p.finish}</span></div><div class="bg-brandIvory border border-brandBeige p-5"><strong class="block mb-2">Insert options</strong><span class="text-slate-600">${p.insert}</span></div></div>
      <div class="bg-white border border-brandBeige p-6"><h2 class="font-serif text-2xl font-bold mb-3">Custom manufacturing brief</h2><p class="text-sm leading-relaxed text-slate-600">This concept is an original ShineleeBox design direction. Final structure, dimensions, board thickness, wrapping paper, insert and finishing are engineered around your product, order quantity and shipping requirements. A physical sample is recommended before mass production.</p></div>
      <div class="bg-brandCharcoal text-brandIvory p-7"><h2 class="font-serif text-2xl font-bold mb-3">Request a custom quote</h2><p class="text-sm text-brandIvory/70 mb-5">Send product dimensions, quantity, artwork and destination for a structure review.</p><div class="flex flex-col sm:flex-row gap-3"><a href="../contact.html?product=${p.id}" class="text-center flex-1 text-xs font-bold bg-brandBurgundy py-4">Send Inquiry</a><a href="https://wa.me/8618818840878" target="_blank" class="text-center flex-1 text-xs font-bold border border-brandIvory/40 py-4">WhatsApp</a></div></div></div>
    </div></section>
    <section class="bg-white border-y border-brandBeige py-16"><div class="max-w-4xl mx-auto px-4"><h2 class="font-serif text-3xl font-bold text-center mb-9">Buyer Questions</h2><div class="space-y-4"><details class="border border-brandBeige p-5"><summary class="font-semibold cursor-pointer">Can this round box be customized for my product?</summary><p class="mt-3 text-sm text-slate-600">Yes. Size, structure, paper, print, finish and insert are developed around your product and brand artwork.</p></details><details class="border border-brandBeige p-5"><summary class="font-semibold cursor-pointer">What should I provide for a quotation?</summary><p class="mt-3 text-sm text-slate-600">Provide product dimensions, target quantity, preferred structure, artwork status, insert needs and destination country.</p></details><details class="border border-brandBeige p-5"><summary class="font-semibold cursor-pointer">Can I order a functional sample?</summary><p class="mt-3 text-sm text-slate-600">Yes. Sampling is recommended to verify fit, opening resistance, insert performance, color and finishing before production.</p></details></div></div></section>
  </main>`;
  let html = productTemplate
    .replace(/<title>[^<]*<\/title>/,`<title>${p.title}</title>`)
    .replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${p.desc}">`)
    .replace(/<link rel="canonical" href="[^"]*">/,`<link rel="canonical" href="${url}">`)
    .replace(/<script type="application\/ld\+json" data-phase2-schema="true">[\s\S]*?<\/script>/,`<script type="application/ld+json" data-round-product-schema="true">${JSON.stringify(schema)}</script>`)
    .replace(/<main class="flex-grow">[\s\S]*?<\/main>/,main);
  fs.writeFileSync(`products/${p.slug}.html`,html);
}

const categoryTemplate = fs.readFileSync('products/rigid-boxes/round-gift-boxes.html','utf8');
function card(p){return `<article class="bg-white border border-brandBeige p-5 flex flex-col luxury-shadow group"><a href="../../products/${p.slug}.html" class="block aspect-square bg-brandIvory overflow-hidden mb-5"><img src="../../images/products/${p.folder}/main.webp" alt="${esc(p.name)}" loading="lazy" decoding="async" class="w-full h-full object-contain group-hover:scale-105 transition-transform duration-500"></a><p class="text-[10px] text-brandGold font-bold uppercase tracking-[0.18em] mb-2">${p.id}</p><h2 class="font-serif text-xl font-bold leading-snug mb-3">${esc(p.name)}</h2><p class="text-sm text-brandCharcoal/65 leading-relaxed mb-5 flex-grow">${p.desc}</p><a href="../../products/${p.slug}.html" class="text-[10px] font-bold uppercase tracking-widest text-brandBurgundy">View product →</a></article>`}
function categoryPage(page){
  const slice=products.slice((page-1)*6,page*6);
  const pageUrl=page===1?'https://slpack.net/products/rigid-boxes/round-gift-boxes.html':'https://slpack.net/products/rigid-boxes/round-gift-boxes-page-2.html';
  const pageTitle=page===1?'Custom Round Gift Boxes & Paper Tubes | ShineleeBox':'Round Gift Box Collection Page 2 | ShineleeBox';
  const pageDescription=page===1?'Custom round gift boxes and cylindrical paper tube packaging for perfume, candles, jewelry, food, beauty and wine. OEM greyboard structures and inserts.':'Explore page 2 of ShineleeBox round packaging: paper tubes and cylindrical rigid gift boxes for tea, wine, cosmetics, flowers, macarons and holiday gift sets.';
  const prev=page===2?'<a href="round-gift-boxes.html" class="border border-brandCharcoal px-5 py-3">← Previous</a>':'';
  const next=page===1?'<a href="round-gift-boxes-page-2.html" class="bg-brandBurgundy text-white px-5 py-3">Next →</a>':'';
  const itemList={'@context':'https://schema.org','@type':'ItemList',name:`Custom Round Gift Boxes — Page ${page}`,numberOfItems:slice.length,itemListElement:slice.map((p,i)=>({'@type':'ListItem',position:(page-1)*6+i+1,url:`https://slpack.net/products/${p.slug}.html`,name:p.name}))};
  const main=`<main class="flex-grow"><section class="bg-brandCharcoal text-brandIvory py-20 border-b border-brandGold/30 text-center"><p class="text-[10px] text-brandGold font-bold uppercase tracking-[0.25em] mb-4">Round Rigid Packaging · Page ${page} of 2</p><h1 class="font-serif text-4xl sm:text-5xl font-bold">Custom Round Gift Boxes &amp; Cylindrical Packaging</h1><p class="mt-5 max-w-3xl mx-auto text-sm sm:text-base leading-relaxed text-brandIvory/75">Original ShineleeBox concepts for perfume, candles, jewelry, chocolate, tea, wine, cosmetics and premium gifting. Every round box can be engineered in custom dimensions with grayboard construction, wrapped paper, branded finishes and fitted inserts.</p></section><section class="py-20 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">${slice.map(card).join('')}</div><nav class="mt-12 flex justify-center items-center gap-4 text-[10px] font-bold uppercase tracking-widest" aria-label="Round gift box pagination">${prev}<span class="px-4 py-3">Page ${page} / 2</span>${next}</nav></section><section class="bg-white border-y border-brandBeige py-16"><div class="max-w-5xl mx-auto px-4 text-center"><h2 class="font-serif text-3xl font-bold">Need a custom cylinder box?</h2><p class="mt-4 text-slate-600">Send your product size, quantity, artwork, insert requirements and destination. We will review the suitable round-box structure and sampling route.</p><a href="../../contact.html" class="inline-flex mt-7 bg-brandBurgundy text-white px-7 py-4 text-[10px] font-bold uppercase tracking-widest">Request Custom Quote</a></div></section></main>`;
  return categoryTemplate
    .replace(/<title>[^<]*<\/title>/,`<title>${pageTitle}</title>`)
    .replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${pageDescription}">`)
    .replace(/<link rel="canonical" href="[^"]*">/,`<link rel="canonical" href="${pageUrl}">`)
    .replace('</head>',`<script type="application/ld+json" data-round-category-schema="true">${JSON.stringify(itemList)}</script>\n</head>`)
    .replace(/<main class="flex-grow">[\s\S]*?<\/main>/,main);
}
fs.writeFileSync('products/rigid-boxes/round-gift-boxes.html',categoryPage(1));
fs.writeFileSync('products/rigid-boxes/round-gift-boxes-page-2.html',categoryPage(2));

console.log(`Built ${products.length} round-box product pages and two category pages.`);
