const fs = require('fs');

const products = [
  {id:'SCB-001', slug:'custom-book-style-chocolate-gift-box', name:'Custom Book-Style Chocolate Gift Box with 12-Cavity Tray', seo:'Custom Book-Style Chocolate Box Manufacturer | ShineleeBox', type:'Book-style rigid box', best:'premium pralines, corporate gifts and seasonal launches', finish:'burgundy textured paper with gold foil', insert:'12-cavity food-grade paper, PET or molded-pulp tray', desc:'Custom book-style chocolate gift box with a hinged cover and fitted 12-cavity tray. OEM rigid packaging with branded paper, foil and food-safe primary-pack options.'},
  {id:'SCB-002', slug:'double-door-book-style-chocolate-box', name:'Luxury Double-Door Book-Style Chocolate Presentation Box', seo:'Double-Door Chocolate Gift Box Manufacturer | ShineleeBox', type:'Double-door book-style rigid box', best:'luxury assortments, VIP gifting and product launches', finish:'forest-green specialty paper with gold foil', insert:'16-cavity food-grade paper or PET tray', desc:'Luxury double-door chocolate presentation box with a central 16-piece tray. Custom rigid packaging for premium confectionery brands, gifting and retail collections.'},
  {id:'SCB-003', slug:'luxury-lid-base-chocolate-box', name:'Luxury Lid-and-Base Chocolate Gift Box with 20-Cavity Tray', seo:'Lid-and-Base Chocolate Box Manufacturer | ShineleeBox', type:'Two-piece lid-and-base rigid box', best:'boxed chocolates, truffles and retail assortments', finish:'midnight-blue paper with champagne-gold detail', insert:'20-cavity food-grade paper, PET or molded-pulp tray', desc:'Luxury lid-and-base chocolate gift box with a fitted 20-cavity tray and premium foil branding. Custom two-piece rigid packaging for chocolate manufacturers.'},
  {id:'SCB-004', slug:'window-lid-chocolate-gift-box', name:'Custom Window Lid Chocolate Gift Box with Geometric Display', seo:'Window Chocolate Gift Box Manufacturer | ShineleeBox', type:'Lid-and-base box with die-cut window', best:'visible praline assortments and retail display', finish:'terracotta and cream paper with blind embossing', insert:'12-cavity food-grade paper or PET tray', desc:'Custom window chocolate gift box with a geometric clear display lid and fitted 12-piece tray. Original rigid packaging for premium confectionery retail.'},
  {id:'SCB-005', slug:'two-drawer-chocolate-gift-box', name:'Two-Drawer Chocolate Gift Box with Ribbon Pulls', seo:'Two-Drawer Chocolate Gift Box Manufacturer | ShineleeBox', type:'Two-tier rigid drawer box', best:'layered assortments, tasting sets and festive gifting', finish:'plum and blush paper with rose-gold foil', insert:'two fitted food-grade paper or PET trays', desc:'Two-drawer chocolate gift box with ribbon pulls and separate fitted trays. Custom rigid packaging for layered assortments, tasting sets and festive gifts.'},
  {id:'SCB-006', slug:'heart-shaped-chocolate-box', name:'Custom Heart-Shaped Chocolate Gift Box with Fitted Tray', seo:'Heart-Shaped Chocolate Box Manufacturer | ShineleeBox', type:'Heart-shaped lid-and-base rigid box', best:'Valentine, wedding and anniversary chocolate gifts', finish:'ruby-red specialty paper with gold foil', insert:'custom heart-shaped food-grade paper or PET tray', desc:'Custom heart-shaped chocolate gift box with a fitted tray for Valentine, wedding and anniversary collections. OEM custom-shape rigid packaging with foil branding.'},
  {id:'SCB-007', slug:'flower-petal-chocolate-gift-box', name:'Flower-Petal Chocolate Gift Box with Six Opening Compartments', seo:'Flower-Petal Chocolate Gift Box Manufacturer | ShineleeBox', type:'Six-petal radial opening rigid box', best:'premium bonbons, launch gifts and celebration assortments', finish:'blush paper with champagne-gold edging', insert:'six food-grade paper compartments plus central well', desc:'Innovative flower-petal chocolate gift box with six radial compartments and a central presentation well. Original custom rigid packaging for premium bonbons.'},
  {id:'SCB-008', slug:'24-day-chocolate-advent-calendar-box', name:'24-Day Chocolate Advent Calendar Box with Drawers', seo:'24-Day Chocolate Advent Calendar Box Manufacturer', type:'Book-style rigid calendar with 24 drawers', best:'Christmas chocolate countdowns and limited-edition campaigns', finish:'midnight-blue paper with constellation gold foil', insert:'24 individual paper drawers sized to wrapped chocolates', desc:'Custom 24-day chocolate advent calendar box with individual pull-out drawers and book-style cover. OEM holiday packaging for chocolate countdown collections.'},
  {id:'SCB-009', slug:'two-tier-rotating-chocolate-box', name:'Two-Tier Rotating Chocolate Presentation Box', seo:'Rotating Chocolate Gift Box Manufacturer | ShineleeBox', type:'Two-tier round rigid box with pivot arm', best:'luxury tasting assortments and shareable gifting', finish:'deep-teal paper with champagne-gold trim', insert:'segmented food-grade paper or PET trays', desc:'Two-tier rotating chocolate presentation box with offset trays and fitted compartments. Custom interactive rigid packaging for luxury confectionery gifts.'},
  {id:'SCB-010', slug:'hexagonal-chocolate-gift-box', name:'Custom Hexagonal Chocolate Gift Box with Wedge Compartments', seo:'Hexagonal Chocolate Gift Box Manufacturer | ShineleeBox', type:'Hexagonal lid-and-base rigid box', best:'artisan truffles, geometric collections and corporate gifts', finish:'charcoal textured paper with copper foil', insert:'six wedge compartments and a central food-grade well', desc:'Custom hexagonal chocolate gift box with six wedge compartments and a central presentation well. Original rigid packaging for artisan truffles and gifting.'}
];

const esc = s => s.replaceAll('&','&amp;').replaceAll('"','&quot;');
const template = fs.readFileSync('products/round-chocolate-box-with-window.html','utf8');

for (const p of products) {
  const url = `https://slpack.net/products/${p.slug}.html`;
  const image = `https://slpack.net/images/products/${p.id}/main.webp`;
  const faq = [
    {q:`Can the ${p.name.toLowerCase()} be customized?`, a:`Yes. ShineleeBox can customize dimensions, wrapped paper, printing, finishing, compartment count and the ${p.insert}. Final specifications depend on the packed chocolate format and project requirements.`},
    {q:'Is the decorative box suitable for direct food contact?', a:'The rigid gift box is normally secondary packaging. Individually wrap the chocolates or use a separately specified food-contact tray, cup or liner, then confirm destination-market requirements before production.'},
    {q:'What information is needed for a chocolate box quotation?', a:'Provide chocolate dimensions, piece count, arrangement, wrapping method, target quantity, artwork status, preferred structure and delivery country. These details allow the box and insert to be engineered together.'},
    {q:'Can I order a sample before mass production?', a:'Yes. A functional sample is recommended to verify chocolate fit, tray retention, opening experience, print color and shipping protection before mass production.'}
  ];
  const schema = {'@context':'https://schema.org','@graph':[
    {'@type':'BreadcrumbList','@id':`${url}#breadcrumb`,itemListElement:[
      {'@type':'ListItem',position:1,name:'Home',item:'https://slpack.net/'},
      {'@type':'ListItem',position:2,name:'Chocolate & Food Packaging',item:'https://slpack.net/applications/chocolate-and-food-packaging.html'},
      {'@type':'ListItem',position:3,name:p.name,item:url}
    ]},
    {'@type':'Product','@id':`${url}#product`,name:p.name,description:p.desc,sku:p.id,url,image:[image],category:'Chocolate & Food Packaging',brand:{'@type':'Brand',name:'ShineleeBox'},manufacturer:{'@id':'https://slpack.net/#organization'},material:'High-density greyboard with custom wrapped paper and a separately specified food-grade primary tray or liner'},
    {'@type':'FAQPage',mainEntity:faq.map(x=>({'@type':'Question',name:x.q,acceptedAnswer:{'@type':'Answer',text:x.a}}))}
  ]};
  const faqHtml = faq.map(x=>`<details class="border border-brandBeige p-5"><summary class="font-semibold cursor-pointer">${esc(x.q)}</summary><p class="mt-3 text-sm text-slate-600">${esc(x.a)}</p></details>`).join('');
  const main = `<main class="flex-grow">
    <nav class="bg-white border-b border-slate-100 py-4 px-4"><div class="max-w-7xl mx-auto text-xs text-slate-500 font-medium flex items-center space-x-2"><a href="../index.html" class="hover:text-brandGold">Home</a><span>/</span><a href="../applications/chocolate-and-food-packaging.html" class="hover:text-brandGold">Chocolate Packaging</a><span>/</span><span class="text-slate-800 font-semibold">${p.id}</span></div></nav>
    <section class="py-14 sm:py-16 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div class="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
      <div class="lg:col-span-6 lg:sticky lg:top-24"><div class="aspect-square bg-white rounded-lg overflow-hidden border border-slate-200 shadow-sm"><img src="../images/products/${p.id}/main.webp" alt="${esc(p.name)} by ShineleeBox" width="1254" height="1254" class="w-full h-full object-contain"></div></div>
      <div class="lg:col-span-6 space-y-8"><div><p class="text-[10px] text-brandGold font-bold uppercase tracking-[0.2em] mb-3">${p.id} · Custom Chocolate Packaging</p><h1 class="font-serif text-3xl sm:text-4xl font-bold text-brandCharcoal mb-4">${esc(p.name)}</h1><p class="text-lg text-slate-600 font-light leading-relaxed">${esc(p.desc)}</p></div>
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm"><div class="bg-brandIvory border border-brandBeige p-5"><strong class="block mb-2">Structure</strong><span class="text-slate-600">${p.type}</span></div><div class="bg-brandIvory border border-brandBeige p-5"><strong class="block mb-2">Best for</strong><span class="text-slate-600">${p.best}</span></div><div class="bg-brandIvory border border-brandBeige p-5"><strong class="block mb-2">Finish direction</strong><span class="text-slate-600">${p.finish}</span></div><div class="bg-brandIvory border border-brandBeige p-5"><strong class="block mb-2">Insert options</strong><span class="text-slate-600">${p.insert}</span></div></div>
      <div class="bg-white border border-brandBeige p-6"><h2 class="font-serif text-2xl font-bold mb-3">Chocolate packaging manufacturing brief</h2><p class="text-sm leading-relaxed text-slate-600">This is an original ShineleeBox concept. The rigid shell uses high-density greyboard rather than MDF wood. Dimensions, board thickness, wrapped paper, insert material and finishing are engineered around the wrapped chocolate, quantity and shipping route. The decorative box is normally secondary packaging; specify a compliant primary tray, cup or liner where food contact applies.</p></div>
      <div class="bg-brandCharcoal text-brandIvory p-7"><h2 class="font-serif text-2xl font-bold mb-3">Request a custom chocolate box quote</h2><p class="text-sm text-brandIvory/70 mb-5">Send chocolate size, piece count, arrangement, quantity, artwork and destination. MOQ may start from 50 pieces for selected projects, subject to structure and finish.</p><div class="flex flex-col sm:flex-row gap-3"><a href="../contact.html?product=${p.id}" class="text-center flex-1 text-xs font-bold bg-brandBurgundy py-4">Send Inquiry</a><a href="https://wa.me/8618818840878?text=I%20am%20interested%20in%20${p.id}" target="_blank" rel="noopener" class="text-center flex-1 text-xs font-bold border border-brandIvory/40 py-4">WhatsApp</a></div></div></div>
    </div></section>
    <section class="bg-white border-y border-brandBeige py-16"><div class="max-w-4xl mx-auto px-4"><h2 class="font-serif text-3xl font-bold text-center mb-3">Chocolate Box Buyer Questions</h2><p class="text-center text-slate-600 mb-9">Practical answers for confectionery brands, distributors and sourcing teams.</p><div class="space-y-4">${faqHtml}</div></div></section>
  </main>`;
  let html = template
    .replace(/<title>[^<]*<\/title>/,`<title>${p.seo}</title>`)
    .replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${esc(p.desc)}">`)
    .replace(/<link rel="canonical" href="[^"]*">/,`<link rel="canonical" href="${url}">`)
    .replace(/<script type="application\/ld\+json" data-round-product-schema="true">[\s\S]*?<\/script>/,`<script type="application/ld+json" data-chocolate-product-schema="true">${JSON.stringify(schema)}</script>`)
    .replace(/<main class="flex-grow">[\s\S]*?<\/main>/,main);
  if (!html.includes('property="og:title"')) html = html.replace('</head>',`<meta property="og:title" content="${esc(p.seo)}"><meta property="og:description" content="${esc(p.desc)}"><meta property="og:type" content="product"><meta property="og:url" content="${url}"><meta property="og:image" content="${image}">\n</head>`);
  fs.writeFileSync(`products/${p.slug}.html`,html);
}

const card = p => `<article class="bg-brandWhite border border-brandBeige hover:border-brandGold transition-all flex flex-col group luxury-shadow"><a href="../products/${p.slug}.html" class="block aspect-square bg-brandIvory overflow-hidden"><img src="../images/products/${p.id}/main.webp" alt="${esc(p.name)}" width="1254" height="1254" loading="lazy" decoding="async" class="w-full h-full object-contain group-hover:scale-105 transition-transform duration-500"></a><div class="p-6 flex flex-col flex-grow"><p class="text-[9px] font-bold text-brandGold uppercase tracking-[0.2em] mb-2">${p.id} · ${p.type}</p><h3 class="font-serif text-xl font-bold leading-snug mb-3"><a href="../products/${p.slug}.html">${esc(p.name)}</a></h3><p class="text-sm text-brandCharcoal/65 leading-relaxed mb-5 flex-grow">${esc(p.desc)}</p><div class="flex justify-between items-center border-t border-brandBeige pt-4"><span class="text-[9px] font-bold text-brandCharcoal/40 uppercase tracking-widest">Custom MOQ</span><a href="../products/${p.slug}.html" class="text-[10px] font-bold uppercase tracking-widest text-brandBurgundy">View details →</a></div></div></article>`;
const collectionSchema = {'@context':'https://schema.org','@type':'ItemList',name:'Original ShineleeBox Chocolate Box Collection',numberOfItems:products.length,itemListElement:products.map((p,i)=>({'@type':'ListItem',position:i+1,name:p.name,url:`https://slpack.net/products/${p.slug}.html`}))};
const section = `<!-- SHINELEE CHOCOLATE COLLECTION START --><section class="py-24 bg-brandIvory border-y border-brandBeige"><div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div class="text-center max-w-4xl mx-auto mb-14"><p class="text-[10px] font-bold text-brandGold uppercase tracking-[0.25em] mb-4">Original ShineleeBox Concepts · 10 Structures</p><h2 class="font-serif text-3xl sm:text-5xl font-bold">Featured Custom Chocolate Box Collection</h2><p class="mt-5 text-brandCharcoal/65 leading-relaxed">Book-style, lid-and-base, drawer, custom-shape, advent calendar and interactive presentation boxes engineered for branded chocolate assortments.</p></div><div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">${products.map(card).join('')}</div></div></section>
<section class="py-20 bg-white"><div class="max-w-5xl mx-auto px-4"><div class="text-center mb-10"><h2 class="font-serif text-3xl sm:text-4xl font-bold">How to Source Custom Chocolate Packaging</h2><p class="mt-4 text-slate-600">Answers designed for brand buyers and AI-assisted sourcing research.</p></div><div class="grid md:grid-cols-2 gap-5"><div class="border border-brandBeige p-6"><h3 class="font-bold mb-2">Which box structure works best for premium chocolates?</h3><p class="text-sm text-slate-600">Book-style boxes create a guided reveal, lid-and-base boxes suit classic retail assortments, drawers support layered collections, and calendars work for countdown campaigns. Choose after confirming piece count, chocolate dimensions and distribution route.</p></div><div class="border border-brandBeige p-6"><h3 class="font-bold mb-2">What should a buyer send for an accurate quote?</h3><p class="text-sm text-slate-600">Send each wrapped chocolate's dimensions, total piece count, desired arrangement, estimated quantity, artwork, finish references and delivery country. A physical product sample is helpful for insert testing.</p></div><div class="border border-brandBeige p-6"><h3 class="font-bold mb-2">Are rigid chocolate boxes food safe?</h3><p class="text-sm text-slate-600">The decorative rigid box is normally secondary packaging. Chocolates should be individually wrapped or placed in an appropriately specified primary tray, cup or liner. Confirm food-contact requirements for the destination market.</p></div><div class="border border-brandBeige p-6"><h3 class="font-bold mb-2">Why sample before mass production?</h3><p class="text-sm text-slate-600">Sampling verifies fit, compartment retention, opening resistance, print color, foil position and shipping protection before production materials are committed.</p></div></div></div></section><!-- SHINELEE CHOCOLATE COLLECTION END -->`;

let category = fs.readFileSync('applications/chocolate-and-food-packaging.html','utf8');
category = category.replace(/\s*<!-- SHINELEE CHOCOLATE COLLECTION START -->[\s\S]*?<!-- SHINELEE CHOCOLATE COLLECTION END -->\s*/,'\n');
category = category.replace(/\s*<script type="application\/ld\+json" data-chocolate-collection-schema="true">[\s\S]*?<\/script>\s*/g,'\n');
const marker = '<section class="py-24 bg-brandCharcoal text-brandIvory">';
if (!category.includes(marker)) throw new Error('Category insertion marker not found');
category = category.replace(marker,`${section}\n${marker}`);
category = category.replace('</head>',`<script type="application/ld+json" data-chocolate-collection-schema="true">${JSON.stringify(collectionSchema)}</script>\n</head>`);
fs.writeFileSync('applications/chocolate-and-food-packaging.html',category);

let llms = fs.readFileSync('llms.txt','utf8').replace(/^- \[Keepsake Boxes\].*\n/m,'');
llms = llms.replace(/\n## Featured Chocolate Packaging[\s\S]*?(?=\n## Application Guides)/g,'');
const llmsBlock = `\n## Featured Chocolate Packaging\n\n${products.map(p=>`- [${p.name}](https://slpack.net/products/${p.slug}.html): ${p.desc}`).join('\n')}\n`;
llms = llms.replace(/\n## Application Guides/,`${llmsBlock}\n## Application Guides`);
fs.writeFileSync('llms.txt',llms);

console.log(`Built ${products.length} chocolate product pages, updated the application collection, and expanded llms.txt.`);
